### ISSUE TITLE
A new (failing) test case for you

### ISSUE THREAD

**Issue by rdebath** [maksverver/BrainfuckVM#1]
It should do nothing immediately, instead it hangs.

``` brainfuck
+[>]<-[-
    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    ++++
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
]
```

**Comment by maksverver** [comment]
Thanks for the bug report! That's an interesting corner case. How did you run into it?

A simpler way to trigger the same bug, is this: >[-<<+>>]

In optimized mode, that loop gets compiled into "add the value at the head of the tape two places to the left", and we end up adding 0 to an invalid memory location (which triggers a segfault in the interpreter that should terminate the program, but currently it doesn't).

I wonder what the right solution should be. It's possible to test before adding, but that introduces a conditional jump, which makes the generated code longer and possibly slower. An alternative would be to  let the signal handler deal with it, which is is a little messy... I'll have to think a little about it.

**Comment by rdebath** [comment]
What I do is to divide this up into two classes. The common class is a short distance and the rare one a long negative distance. Accesses to the 'right' of the `[` are known to be safe, (the tape is 'infinite') so if all accesses are above the `[` no condition is needed. I then add a small number of cells to the 'left' of the starting point. Because I know the `[` must be to the right of the starting point I can safely access that many cells to the left of the `[`. If the range is larger than that I put the condition in.

The [Mandelbrot program](https://github.com/rdebath/Brainfuck/blob/master/testing/Mandelbrot.b) from [here](http://esoteric.sange.fi/brainfuck/utils/mandelbrot/) witth [commonly](http://esolangs.org/wiki/User:Rdebath#Performance) trigger the problem.

The test seems to hit more interpreters than I though, especially with a long jump, so now I've written a [new test for it](https://github.com/rdebath/Brainfuck/blob/master/testing/Skiploop.b).

BTW: the `+[>]<-` thing is my favourite fragment for defeating optimisers.

**Comment by rdebath** [comment]
I see you'd like some benchmarking ...
It looks like the ones I'm using for scoring are unchanged, the bug is fixed. Of the others, 'Collatz' and 'Factor' look substantially slower, however, several of the others are actually quicker!

<table style="font-family:sans-serif;font-size:10pt;border-collapse:collapse;" bgcolor=white border=1px solid #000 >
<tr>
<th>Interpreter<th>Total<th>Score
<th><a href="https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b">Bitwidth</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Endtest.b">Endtest</a><th>Counter<th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Prime8.b">Prime8</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Hanoi.b">Hanoi</a><th><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Precalc.b">Precalc</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Beer.b">Beer</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Collatz.b">Collatz</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Golden.b">Golden</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Long.b">Long</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/SelfInt.b">SelfInt</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Euler1.b">Euler1</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Life.b">Life</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Factor.b">Factor</a><th><a href="http://esoteric.sange.fi/brainfuck/utils/mandelbrot/">Mandel</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Skiploop.b">Skiploop</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Bench.b">Bench</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/OptimTease.b">BigTxt</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/LostKng.b">LostKng</a><th><a href="https://github.com/matslina/awib">awib</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Zozotez.b">Zozotez</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Euler5.b">Euler5</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Prime.b">Prime</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/PIdigits.b">PIdigits</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/PIdigits-as.b">PIdg-as</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/PIdigits-cp.b">PIdg-cp</a><tr>
<td><td><td>
<td>105<td>118<td>122<td>113<td>111<td><td>114<td>113<td>112<td>111<td>111<td>110<td>106<td>102<td>101<td>101<td>98<td>94<td>91<td>83<td>64<td>35<td>23<td>19<td>49<td>108<td>69
<tr bgcolor="#000"><td><td><td><td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/rdebath/Brainfuck/tree/master/bf2any">rdb_bf2jit</a> <td> 173s <td> 22.04<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f608" ><b>1.05s</b><td bgcolor="#00fe00" >0.03s<td bgcolor="#00fe00" ><i>0.01s</i><td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f00e" >0.69s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fc02" >0.2s<td bgcolor="#00e01e" >2.91s<td bgcolor="#00fd01" >0.15s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f509" >0.15s<td bgcolor="#00f00e" >1.01s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00fd01" >0.03s<td bgcolor="#00fd01" >0.09s<td bgcolor="#00fc02" ><b>0.02s</b><td bgcolor="hotpink" >117s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#433bc3" >48.5s<td bgcolor="#00f806" ><b>0.48s</b><td bgcolor="#00f806" >0.69s
<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/rdebath/Brainfuck/tree/master/tritium">tritium_q</a> <td> 191.6s <td> 21.64<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f608" ><b>1.05s</b><td bgcolor="#00fe00" ><b>0.02s</b><td bgcolor="#00fe00" >0.04s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f40a" ><i>0.01s</i><td bgcolor="#00f10d" ><b>0.65s</b><td bgcolor="#00f608" >0.02s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00e915" >2.05s<td bgcolor="#00fc02" >0.37s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f509" >0.15s<td bgcolor="#00f10d" ><b>0.91s</b><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#008876" >2.67s<td bgcolor="#00fb03" >0.23s<td bgcolor="#00f707" >0.07s<td bgcolor="hotpink" >43.6s<td bgcolor="hotpink" >122s<td bgcolor="#606000" >Skip<td bgcolor="#00ba44" >16.9s<td bgcolor="#00f806" >0.49s<td bgcolor="#00fb03" ><b>0.32s</b>
<tr><td bgcolor="#E0FFE0" > <a href="https://savannah.nongnu.org/projects/libbf">libbf</a> <td> 15.47s <td> 18.48<td bgcolor="yellow" >Zombie8<td bgcolor="#00A000" >0xFF<td bgcolor="#00f40a" >1.23s<td bgcolor="#00fe00" ><b>0.02s</b><td bgcolor="#00fd01" >0.05s<td ><td bgcolor="yellow" >0s<td bgcolor="yellow" >0.01s<td bgcolor="#00ef0f" >0.72s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fb03" >0.22s<td bgcolor="#00df1f" >3s<td bgcolor="red" >200s<td bgcolor="yellow" >0.01s<td bgcolor="#00f509" >0.15s<td bgcolor="#00f00e" >1s<td bgcolor="#00fd01" ><i>0.01s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00e816" >0.5s<td bgcolor="#00827c" >7.99s<td style="border:2px solid #F60" bgcolor="yellow" >0.03s<td bgcolor="#606000" >Skip<td bgcolor="yellow" >0.05s<td bgcolor="yellow" >0.03s<td bgcolor="red" >200s<td bgcolor="#00f707" >0.56s<td bgcolor="red" >100s
<tr><td bgcolor="#E0FFE0" > <a href="http://lvogel.free.fr/bf.html">bfli_nb</a> <td> 138.2s <td> 14.38<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f40a" >1.31s<td bgcolor="#00f905" >0.31s<td bgcolor="#00fd01" >0.05s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ea14" >0.02s<td bgcolor="#00f10d" ><b>0.65s</b><td bgcolor="#00f608" >0.02s<td bgcolor="#00fc02" >0.2s<td bgcolor="#00ea14" ><b>2.01s</b><td bgcolor="#00fd01" >0.13s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f608" ><b>0.13s</b><td bgcolor="#00f10d" >0.92s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00fe00" >0.02s<td bgcolor="#00fe00" >0.05s<td style="border:2px solid #F60" bgcolor="yellow" >0.01s<td bgcolor="hotpink" >94.5s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#146a94" >36.8s<td bgcolor="#00f707" >0.54s<td bgcolor="#00f905" >0.55s
<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/maksverver/BrainfuckVM">maksverver_BrainfuckVM</a> <td> 166.6s <td> 13.05<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f509" >1.21s<td bgcolor="#00f509" >0.58s<td bgcolor="#00fd01" >0.05s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00e915" >1s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fa04" >0.3s<td bgcolor="#00e01e" >2.93s<td bgcolor="#00fd01" >0.14s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f10d" >0.2s<td bgcolor="#00ed11" >1.19s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f806" >0.15s<td bgcolor="#00fd01" >0.07s<td bgcolor="#00fc02" ><b>0.02s</b><td bgcolor="hotpink" >112s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#3747b7" >45.5s<td bgcolor="#00f707" >0.54s<td bgcolor="#00f806" >0.69s
<tr><td bgcolor="#E0FFE0" > old_maksverver_bf <td> 172.5s <td> 13.05<td bgcolor="yellow" >8bit?<td bgcolor="#00E000" >Leave<td bgcolor="#00f509" >1.21s<td bgcolor="#00f509" >0.58s<td bgcolor="#00fd01" >0.05s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f10d" >0.66s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fb03" >0.28s<td bgcolor="#00e01e" >2.9s<td bgcolor="#00fd01" >0.15s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f509" >0.15s<td bgcolor="red" >80s<td bgcolor="red" >120s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f707" >0.16s<td bgcolor="#00fd01" >0.07s<td bgcolor="#00fc02" ><b>0.02s</b><td bgcolor="hotpink" >118s<td bgcolor="red" >200s<td bgcolor="red" >80s<td bgcolor="#3d41bd" >47s<td bgcolor="#00f707" >0.53s<td bgcolor="#00f707" >0.71s
<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/rmmh/beefit">rmmh_beefit</a> <td> 49.96s <td> 12.78<td bgcolor="#00A000" >8bit<td bgcolor="#00A000" >0xFF<td bgcolor="#00f509" >1.15s<td bgcolor="#00f30b" >0.67s<td bgcolor="#00fd01" >0.06s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ef0f" >0.72s<td bgcolor="#00fa04" ><i>0.01s</i><td bgcolor="#00fc02" >0.21s<td bgcolor="#00e01e" >2.98s<td style="border:2px solid #F60" bgcolor="yellow" >0s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f30b" >0.17s<td bgcolor="#00f10d" ><b>0.91s</b><td style="border:2px solid #F60" bgcolor="yellow" >0s<td bgcolor="#00ff00" ><i>0s</i><td style="border:2px solid #F60" bgcolor="yellow" >0s<td style="border:2px solid #F60" bgcolor="yellow" >0s<td style="border:2px solid #F60" bgcolor="yellow" >0.02s<td style="border:2px solid #F60" bgcolor="yellow" >0s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#2856a8" >41.9s<td bgcolor="#00f707" >0.54s<td bgcolor="#00f806" >0.63s
</table>

HTML source for the colours.

``` html
<table style="font-family:sans-serif;font-size:10pt;border-collapse:collapse;" bgcolor=white border=1px solid #000 >
<tr>
<th>Interpreter<th>Total<th>Score
<th><a href="https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b">Bitwidth</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Endtest.b">Endtest</a><th>Counter<th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Prime8.b">Prime8</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Hanoi.b">Hanoi</a><th><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Precalc.b">Precalc</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Beer.b">Beer</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Collatz.b">Collatz</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Golden.b">Golden</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Long.b">Long</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/SelfInt.b">SelfInt</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Euler1.b">Euler1</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Life.b">Life</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Factor.b">Factor</a><th><a href="http://esoteric.sange.fi/brainfuck/utils/mandelbrot/">Mandel</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Skiploop.b">Skiploop</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Bench.b">Bench</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/OptimTease.b">BigTxt</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/LostKng.b">LostKng</a><th><a href="https://github.com/matslina/awib">awib</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Zozotez.b">Zozotez</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Euler5.b">Euler5</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/Prime.b">Prime</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/PIdigits.b">PIdigits</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/PIdigits-as.b">PIdg-as</a><th><a href="https://github.com/rdebath/Brainfuck/blob/master/testing/PIdigits-cp.b">PIdg-cp</a><tr>
<td><td><td>
<td>105<td>118<td>122<td>113<td>111<td><td>114<td>113<td>112<td>111<td>111<td>110<td>106<td>102<td>101<td>101<td>98<td>94<td>91<td>83<td>64<td>35<td>23<td>19<td>49<td>108<td>69

<tr bgcolor="#000"><td><td><td><td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>
<td>

<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/rdebath/Brainfuck/tree/master/bf2any">rdb_bf2jit</a> <td> 173s <td> 22.04<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f608" ><b>1.05s</b><td bgcolor="#00fe00" >0.03s<td bgcolor="#00fe00" ><i>0.01s</i><td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f00e" >0.69s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fc02" >0.2s<td bgcolor="#00e01e" >2.91s<td bgcolor="#00fd01" >0.15s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f509" >0.15s<td bgcolor="#00f00e" >1.01s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00fd01" >0.03s<td bgcolor="#00fd01" >0.09s<td bgcolor="#00fc02" ><b>0.02s</b><td bgcolor="hotpink" >117s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#433bc3" >48.5s<td bgcolor="#00f806" ><b>0.48s</b><td bgcolor="#00f806" >0.69s

<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/rdebath/Brainfuck/tree/master/tritium">tritium_q</a> <td> 191.6s <td> 21.64<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f608" ><b>1.05s</b><td bgcolor="#00fe00" ><b>0.02s</b><td bgcolor="#00fe00" >0.04s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f40a" ><i>0.01s</i><td bgcolor="#00f10d" ><b>0.65s</b><td bgcolor="#00f608" >0.02s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00e915" >2.05s<td bgcolor="#00fc02" >0.37s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f509" >0.15s<td bgcolor="#00f10d" ><b>0.91s</b><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#008876" >2.67s<td bgcolor="#00fb03" >0.23s<td bgcolor="#00f707" >0.07s<td bgcolor="hotpink" >43.6s<td bgcolor="hotpink" >122s<td bgcolor="#606000" >Skip<td bgcolor="#00ba44" >16.9s<td bgcolor="#00f806" >0.49s<td bgcolor="#00fb03" ><b>0.32s</b>

<tr><td bgcolor="#E0FFE0" > <a href="https://savannah.nongnu.org/projects/libbf">libbf</a> <td> 15.47s <td> 18.48<td bgcolor="yellow" >Zombie8<td bgcolor="#00A000" >0xFF<td bgcolor="#00f40a" >1.23s<td bgcolor="#00fe00" ><b>0.02s</b><td bgcolor="#00fd01" >0.05s<td ><td bgcolor="yellow" >0s<td bgcolor="yellow" >0.01s<td bgcolor="#00ef0f" >0.72s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fb03" >0.22s<td bgcolor="#00df1f" >3s<td bgcolor="red" >200s<td bgcolor="yellow" >0.01s<td bgcolor="#00f509" >0.15s<td bgcolor="#00f00e" >1s<td bgcolor="#00fd01" ><i>0.01s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00e816" >0.5s<td bgcolor="#00827c" >7.99s<td style="border:2px solid #F60" bgcolor="yellow" >0.03s<td bgcolor="#606000" >Skip<td bgcolor="yellow" >0.05s<td bgcolor="yellow" >0.03s<td bgcolor="red" >200s<td bgcolor="#00f707" >0.56s<td bgcolor="red" >100s

<tr><td bgcolor="#E0FFE0" > <a href="http://lvogel.free.fr/bf.html">bfli_nb</a> <td> 138.2s <td> 14.38<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f40a" >1.31s<td bgcolor="#00f905" >0.31s<td bgcolor="#00fd01" >0.05s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ea14" >0.02s<td bgcolor="#00f10d" ><b>0.65s</b><td bgcolor="#00f608" >0.02s<td bgcolor="#00fc02" >0.2s<td bgcolor="#00ea14" ><b>2.01s</b><td bgcolor="#00fd01" >0.13s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f608" ><b>0.13s</b><td bgcolor="#00f10d" >0.92s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00fe00" >0.02s<td bgcolor="#00fe00" >0.05s<td style="border:2px solid #F60" bgcolor="yellow" >0.01s<td bgcolor="hotpink" >94.5s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#146a94" >36.8s<td bgcolor="#00f707" >0.54s<td bgcolor="#00f905" >0.55s

<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/maksverver/BrainfuckVM">maksverver_BrainfuckVM</a> <td> 166.6s <td> 13.05<td bgcolor="#00A000" >8bit<td bgcolor="#00E000" >Leave<td bgcolor="#00f509" >1.21s<td bgcolor="#00f509" >0.58s<td bgcolor="#00fd01" >0.05s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00e915" >1s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fa04" >0.3s<td bgcolor="#00e01e" >2.93s<td bgcolor="#00fd01" >0.14s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f10d" >0.2s<td bgcolor="#00ed11" >1.19s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f806" >0.15s<td bgcolor="#00fd01" >0.07s<td bgcolor="#00fc02" ><b>0.02s</b><td bgcolor="hotpink" >112s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#3747b7" >45.5s<td bgcolor="#00f707" >0.54s<td bgcolor="#00f806" >0.69s

<tr><td bgcolor="#E0FFE0" > old_maksverver_bf <td> 172.5s <td> 13.05<td bgcolor="yellow" >8bit?<td bgcolor="#00E000" >Leave<td bgcolor="#00f509" >1.21s<td bgcolor="#00f509" >0.58s<td bgcolor="#00fd01" >0.05s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f10d" >0.66s<td bgcolor="#00f608" >0.02s<td bgcolor="#00fb03" >0.28s<td bgcolor="#00e01e" >2.9s<td bgcolor="#00fd01" >0.15s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f509" >0.15s<td bgcolor="red" >80s<td bgcolor="red" >120s<td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00f707" >0.16s<td bgcolor="#00fd01" >0.07s<td bgcolor="#00fc02" ><b>0.02s</b><td bgcolor="hotpink" >118s<td bgcolor="red" >200s<td bgcolor="red" >80s<td bgcolor="#3d41bd" >47s<td bgcolor="#00f707" >0.53s<td bgcolor="#00f707" >0.71s

<tr><td bgcolor="#E0FFE0" > <a href="https://github.com/rmmh/beefit">rmmh_beefit</a> <td> 49.96s <td> 12.78<td bgcolor="#00A000" >8bit<td bgcolor="#00A000" >0xFF<td bgcolor="#00f509" >1.15s<td bgcolor="#00f30b" >0.67s<td bgcolor="#00fd01" >0.06s<td ><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ff00" ><i>0s</i><td bgcolor="#00ef0f" >0.72s<td bgcolor="#00fa04" ><i>0.01s</i><td bgcolor="#00fc02" >0.21s<td bgcolor="#00e01e" >2.98s<td style="border:2px solid #F60" bgcolor="yellow" >0s<td bgcolor="#00fe00" ><i>0.01s</i><td bgcolor="#00f30b" >0.17s<td bgcolor="#00f10d" ><b>0.91s</b><td style="border:2px solid #F60" bgcolor="yellow" >0s<td bgcolor="#00ff00" ><i>0s</i><td style="border:2px solid #F60" bgcolor="yellow" >0s<td style="border:2px solid #F60" bgcolor="yellow" >0s<td style="border:2px solid #F60" bgcolor="yellow" >0.02s<td style="border:2px solid #F60" bgcolor="yellow" >0s<td bgcolor="#606000" >Skip<td bgcolor="#606000" >Skip<td bgcolor="#2856a8" >41.9s<td bgcolor="#00f707" >0.54s<td bgcolor="#00f806" >0.63s

</table>

```

**Comment by maksverver** [comment]
Interesting! I figured it could go either way: if the cell is usually nonzero, then the check is just overhead. If the cell is sometimes zero, you could save some time by jumping over the loop, which is especially useful because memory access is relatively expensive. I didn't have the benchmarks to back it up, though.

What do the `skip` values mean in the benchmark results?

(By the way, if you're in the business of building a benchmark suite: there's at least one more benchmark in my repo that you might want to borrow.)

**Comment by rdebath** [comment]
The "skip" means it didn't complete in the time allotted and it wasn't really expected to because it's a program that only runs in a reasonable time if the cells are a particular size. "Prime" is calculating all the primes up to 1030, it requires an interpreter that can do "simple loops" on a 16bit+ cell. Euler5 isn't quite as strict but it needs a very fast instruction rate to compensate for the "cell quadrupling" of 8bit cells, OTOH Zozotez just needs 'pretty quick' instructions to compensate for the [cell expansion conversions](http://esolangs.org/wiki/Brainfuck_bitwidth_conversions).

In the other direction the "Bench" program has these instruction counts:

```
Commands executed on 8bit: 268436272
Commands executed on 16bit: 4503599627371312
Commands executed on 32bit: 1267650600228229401496703206192
```

It can only run on 32bit if the optimiser is exceptional.

**Comment by maksverver** [comment]
Prime and Euler5 seem to run fast enough, but not produce the correct results. I assume they don't work with 8-bit cells?

Personally I consider the 8-bit cell width restriction an essential part of Brainfuck. Programs that assume arbitrarily large cells aren't true Brainfuck programs, as far as I'm concerned. (It always annoys me a bit when people pass them off as such, especially considering how much more difficult it is to write real Brainfuck code.)

**Comment by rdebath** [comment]
Use these variants:

https://github.com/rdebath/Brainfuck/blob/master/testing/Euler5-multisize.b
https://github.com/rdebath/Brainfuck/blob/master/testing/Prime-doubled.b

The size restriction to the arbitrary 8bits makes no difference IMO, If you need larger numbers doubling or quadrupling it isn't difficult. If those don't work for you the usual fallback is to use decimal because printing out the numbers then becomes trivial.

Hmmm, I think I might change the links on those particular headings.

**Comment by maksverver** [comment]
Thanks for the links to the multisize versions!

> The size restriction to the arbitrary 8bits makes no difference IMO, If you need larger numbers doubling or quadrupling it isn't difficult.

Sure, any higher-level language can be compiled down to Brainfuck, since Brainfuck is a Turing-complete language.

However, the point of writing Brainfuck in the first place is to challenge yourself. Writing code in a higher-level dialect then compiling it down to real Brainfuck is less of a challenge and thus defeats the point of using Brainfuck in the first place. In my opinion, programs written in higher-level languages don't deserve to be called Brainfuck programs.

If I write a program in C and use the compiler to generate the appropriate assembly code, I didn't write assembly code.

Moreover, generated Brainfuck code is typically much larger, less readable (yes, less readable than regular Brainfuck :-P) and usually slower than hand-crafted code. (All of these properties are apparent from the multisize programs you posted.)

> If those don't work for you the usual fallback is to use decimal because printing out the numbers then becomes trivial.

Right, which is a much smarter approach anyway, because it leads to code that isn't limited by the size of the cell.

**Comment by rdebath** [comment]
Yes, I do agree with you for the most part, but I'm saying that it doesn't matter what base you store the numbers in. The algorithms you use to increase the size from a single "digit" are the same if you use base 10, base 100, base 256, base 4294967296 or any other that's appropriate. They are those addition, subtraction, multiplication and division you learnt in primary school. If anything base 10 would easier as it's more familiar. Then also with a non-optimising interpreter base 100 will probably be faster for every case where base 10 is faster than the others (ie: with lots of printing out of large base 10 numbers)

As for readability, yes, for any generated code the readability is usually worse. But that doesn't really apply to simple automated cell doubling. After all if I'd followed my own suggestion the first section of that "multisize" file would be exactly the same as the pure 32bit version, just with the comments that tell you that you don't need to bother to look at the other parts.

Oh, BTW limiting yourself to to using base 10 and so using less than half of each cell is NOT the best way to make unbounded integers.
